(deftheme habamax "A port of the habamax colorscheme from Vim to Emacs.")

(let ((class '((class color) (min-colors 89)))
      (terminal-colors '("#1c1c1c" "#d75f5f" "#87af87" "#afaf87" "#5f87af" "#af87af" "#5f8787" "#9e9e9e"
                         "#767676" "#d7875f" "#afd7af" "#d7d787" "#87afd7" "#d7afd7" "#87afaf" "#bcbcbc"))
      (habamax-fg "#bcbcbc")
      (habamax-bg "#1c1c1c")
      (habamax-comment "#767676")
      (habamax-string "#87af87")
      (habamax-type "#87afd7")
      (habamax-constant "#d7875f")
      (habamax-warning "#d7875f")
      (habamax-function "#af87af")
      (habamax-variable "#87afaf")
      (habamax-keyword "#af87af")
      (habamax-error-bg "#d75f5f")
      (habamax-error-fg "#1c1c1c")
      (habamax-info-bg "#d7d787")
      (habamax-info-fg "#1c1c1c")
      (habamax-warning-bg "#af87af")
      (habamax-warning-fg "#1c1c1c")
      (habamax-visual-bg "#87afaf")
      (habamax-visual-non-bg "#5f8787")
      (habamax-pmenu-bg "#3a3a3a")
      (habamax-pmenu-sel-bg "#afaf87")
      (habamax-tabline-bg "#767676")
      (habamax-tabline-fg "#1c1c1c")
      (habamax-statusline-bg "#9e9e9e")
      (habamax-statusline-fg "#1c1c1c")
      (habamax-cursorline-bg "#303030")
      (habamax-search-bg "#87af87")
      (habamax-search-fg "#1c1c1c")
      (habamax-incsearch-bg "#ffaf5f")
      (habamax-incsearch-fg "#1c1c1c")
      (habamax-matchparen-bg "#1c1c1c")
      (habamax-matchparen-fg "#5f8787"))

  (custom-theme-set-faces
   'habamax
   `(default ((,class (:foreground ,habamax-fg :background ,habamax-bg))))
   `(cursor ((,class (:background "#FFFFFF"))))
   `(highlight ((,class (:background ,habamax-visual-bg))))
   `(region ((,class (:background ,habamax-visual-bg))))
   `(secondary-selection ((,class (:background ,habamax-visual-non-bg))))
   `(isearch ((,class (:foreground ,habamax-search-fg :background ,habamax-search-bg))))
   `(lazy-highlight ((,class (:foreground ,habamax-incsearch-fg :background ,habamax-incsearch-bg))))
   `(mode-line ((,class (:foreground ,habamax-statusline-fg :background ,habamax-statusline-bg))))
   `(mode-line-inactive ((,class (:foreground ,habamax-statusline-fg :background ,habamax-tabline-bg))))
   `(fringe ((,class (:background ,habamax-bg))))
   `(minibuffer-prompt ((,class (:foreground ,habamax-fg))))
   `(font-lock-builtine-face ((,class (:foreground "#FF8700" :weight bold))))
   `(font-lock-comment-face ((,class (:foreground ,habamax-comment))))
   `(font-lock-constant-face ((,class (:foreground ,habamax-constant))))
   `(font-lock-function-name-face ((,class (:foreground ,habamax-function))))
   `(font-lock-keyword-face ((,class (:foreground "#FF8700" :weight bold))))
   `(font-lock-string-face ((,class (:foreground ,habamax-string))))
   `(font-lock-type-face ((,class (:foreground ,habamax-type))))
   `(font-lock-variable-name-face ((,class (:foreground ,habamax-variable))))
   `(font-lock-warning-face ((,class (:foreground ,habamax-warning))))
   `(line-number ((,class (:foreground ,habamax-comment))))
   `(line-number-current-line ((,class (:foreground ,habamax-fg :weight bold))))
   `(vertical-border ((,class (:foreground ,habamax-tabline-bg))))
   `(hl-line ((,class (:background ,habamax-cursorline-bg))))
   `(show-paren-match ((,class (:foreground ,habamax-matchparen-fg :background ,habamax-matchparen-bg))))
   `(error ((,class (:foreground ,habamax-error-fg :background ,habamax-error-bg))))
   `(warning ((,class (:foreground ,habamax-warning-fg :background ,habamax-warning-bg))))
   `(success ((,class (:foreground ,habamax-info-fg :background ,habamax-info-bg))))
   `(tooltip ((,class (:background ,habamax-pmenu-bg :foreground ,habamax-fg))))
   `(company-tooltip ((,class (:background ,habamax-pmenu-bg :foreground ,habamax-fg))))
   `(company-tooltip-selection ((,class (:background ,habamax-pmenu-sel-bg :foreground ,habamax-fg))))
   `(company-tooltip-annotation ((,class (:background ,habamax-pmenu-bg :foreground ,habamax-fg))))
   `(company-scrollbar-bg ((,class (:background ,habamax-pmenu-bg))))
   `(company-scrollbar-fg ((,class (:background ,habamax-tabline-bg))))
   `(company-tooltip-common ((,class (:foreground ,habamax-fg))))
   `(company-tooltip-common-selection ((,class (:foreground ,habamax-fg))))
   `(company-preview ((,class (:background ,habamax-pmenu-bg :foreground ,habamax-fg))))
   `(company-preview-common ((,class (:foreground ,habamax-fg))))
   `(company-preview-search ((,class (:foreground ,habamax-fg))))
   `(company-echo ((,class (:foreground ,habamax-fg))))
   `(company-echo-common ((,class (:foreground ,habamax-fg))))))

(provide-theme 'habamax)
