[window]
title = "terminal"
opacity = 1.0
decorations = "Full"

[font]
size = 25.5

[font.bold]
family = "Iosevka"
style = "Bold"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = []

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"
